<?xml version="1.0" encoding="utf-8"?><Database Name="Bookstore" Class="BookstoreDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=(LocalDB)\MSSQLLocalDB;AttachDbFilename=C:\git\Programming-Technologies\Task_1\Bookstore\DataTests\Instrumentation\Bookstore.mdf;Integrated Security=True;Connect Timeout=30" SettingsObjectName="DataLayer.Properties.Settings" SettingsPropertyName="BookstoreConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Actor" Member="Actors">
    <Type Name="Actor">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="Actor_Event" Member="Events" ThisKey="Id" OtherKey="ActorId" Type="Event" />
    </Type>
  </Table>
  <Table Name="dbo.Stock" Member="Stocks">
    <Type Name="Stock">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="BookId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Number" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Book_Stock" Member="Book" ThisKey="BookId" OtherKey="Id" Type="Book" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Book" Member="Books">
    <Type Name="Book">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ISBN" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Author" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Price" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Association Name="Book_Stock" Member="Stocks" ThisKey="Id" OtherKey="BookId" Type="Stock" />
      <Association Name="Book_Invoice" Member="Invoices" ThisKey="Id" OtherKey="BookId" Type="Invoice" />
    </Type>
  </Table>
  <Table Name="dbo.Event" Member="Events">
    <Type Name="Event">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ActorId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="InvoiceId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Sale" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="Actor_Event" Member="Actor" ThisKey="ActorId" OtherKey="Id" Type="Actor" IsForeignKey="true" />
      <Association Name="Invoice_Event" Member="Invoice" ThisKey="InvoiceId" OtherKey="Id" Type="Invoice" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Invoice" Member="Invoices">
    <Type Name="Invoice">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="BookId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Price" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="Number" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Invoice_Event" Member="Events" ThisKey="Id" OtherKey="InvoiceId" Type="Event" />
      <Association Name="Book_Invoice" Member="Book" ThisKey="BookId" OtherKey="Id" Type="Book" IsForeignKey="true" />
    </Type>
  </Table>
</Database>